server:
  port: 8000
  servlet:
    context-path: /club

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hzw_bk?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/hzw_bk?serverTimezone=UTC
    schemas: hzw_bk
    user: root
    password: 123456
    baseline-on-migrate: false
    mvc:
      static-path-pattern: /**


####mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hikvision.background.kerny
  configuration:
    map-underscore-to-camel-case: true

###logback
logging:
  config: classpath:config/logback-test.xml
resources: # 指定静态资源的路径
  static-locations: classpath:/static/
