DROP TABLE IF EXISTS `HOTEL_FACILITY_MODULE`;
CREATE TABLE HOTEL_FACILITY_MODULE (
	`ID` INT NULL COMMENT '主键',
	`FACILITY_ID` INT NULL COMMENT '模块编号',
	`FACILITY` TEXT NULL COMMENT '酒店服务名称',
	`IMG_PATH` VARCHAR(255) NULL DEFAULT NULL COMMENT '图标',
	`DELETE_FLAG` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '0',
  `CREATE_USER` int(255) NULL DEFAULT NULL COMMENT '创建用户',
  `UPDATE_USER` int(11) NULL DEFAULT NULL COMMENT '更新用户',
  `CREATE_TIME` timestamp(0) NOT NULL DEFAULT current_timestamp() COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;
