DROP TABLE IF EXISTS `HOTEL`;
CREATE TABLE HOTEL (
	`ID` INT NULL AUTO_INCREMENT COMMENT '主键',
	`HOTEL_ID` varchar(100) NULL COMMENT '酒店编号',
	`HOTEL_NAME` varchar(100) NULL COMMENT '酒店名称',
	`HOTEL_LOCATION` varchar(100) NULL COMMENT '酒店位置',
	`HOTEL_SCORE` varchar(100) NULL COMMENT '酒店评分',
	`HOTEL_RATE` int NULL COMMENT '酒店星级',
	`HOTEL_INTIME` TIMESTAMP NULL COMMENT '酒店入住时间',
	`HOTEL_OUTTIME` TIMESTAMP NULL COMMENT '酒店离店时间',
	`HOTEL_BUILDTIME` TIME NULL COMMENT '建造时间',
	`HOTEL_REBUILDTIME` TIME NULL COMMENT '装修时间',
	`HOTEL_ROOMS` INT NULL COMMENT '酒店规模',
	`MAIN_FACILITY` TEXT NULL COMMENT '主要设施',
	`HOTEL_SERVICE` TEXT NULL COMMENT '酒店服务',
	`HOTEL_FACILITY` TEXT NULL COMMENT '酒店设施',
	`ROOM_FACILITY` TEXT NULL COMMENT '房间设施',
	`HOTEL_HELP` TEXT NULL COMMENT '酒店攻略',
	`HOTEL_IMG` varchar(1000) NULL COMMENT '酒店图片',
	`LAT` VARCHAR(100) NULL COMMENT '点位信息纬度',
	`LNG` VARCHAR(100) NULL COMMENT '点位信息经度',
	`DELETE_FLAG` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '0',
  `CREATE_USER` int(255) NULL DEFAULT NULL,
  `UPDATE_USER` int(11) NULL DEFAULT NULL,
  `CREATE_TIME` timestamp(0) NOT NULL DEFAULT current_timestamp() COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`) USING BTREE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;